[
    {
        "id": 1,
        "ticker": "AAPL",
        "exchange": "NASDAQ",
        "name": "Apple Inc.",
        "initialPrice": 22.00,
        "currentPrice": 193.00,
        "description": "Apple Inc. is an American multinational technology company that specializes in consumer electronics, software, and online services.",
        "ipoDate": "1980-12-12",
        "siteURL": "https://www.apple.com",
        "industries": ["Technology", "Consumer Electronics"],
        "icon": "https://logo.clearbit.com/apple.com",
        "favorited": true,
        "timesBought": 102
    },
    {
        "id": 2,
        "ticker": "GOOGL",
        "exchange": "NASDAQ",
        "name": "Alphabet Inc.",
        "initialPrice": 50.00,
        "currentPrice": 2850.00,
        "description": "Alphabet Inc. is an American multinational conglomerate created through a corporate restructuring of Google.",
        "ipoDate": "2004-08-19",
        "siteURL": "https://www.abc.xyz",
        "industries": ["Technology", "Internet"],
        "icon": "https://logo.clearbit.com/abc.xyz",
        "favorited": false,
        "timesBought": 230
    },
    {
        "id": 3,
        "ticker": "AMZN",
        "exchange": "NASDAQ",
        "name": "Amazon.com Inc.",
        "initialPrice": 18.00,
        "currentPrice": 3375.00,
        "description": "Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence.",
        "ipoDate": "1997-05-15",
        "siteURL": "https://www.amazon.com",
        "industries": ["Technology", "E-commerce"],
        "icon": "https://logo.clearbit.com/amazon.com",
        "favorited": true,
        "timesBought": 150
    },
    {
        "id": 4,
        "ticker": "MSFT",
        "exchange": "NASDAQ",
        "name": "Microsoft Corporation",
        "initialPrice": 21.00,
        "currentPrice": 299.00,
        "description": "Microsoft Corporation is an American multinational technology company with headquarters in Redmond, Washington.",
        "ipoDate": "1986-03-13",
        "siteURL": "https://www.microsoft.com",
        "industries": ["Technology", "Software"],
        "icon": "https://logo.clearbit.com/microsoft.com",
        "favorited": true,
        "timesBought": 180
    },
    {
        "id": 5,
        "ticker": "TSLA",
        "exchange": "NASDAQ",
        "name": "Tesla, Inc.",
        "initialPrice": 17.00,
        "currentPrice": 650.00,
        "description": "Tesla, Inc. is an American electric vehicle and clean energy company based in Palo Alto, California.",
        "ipoDate": "2010-06-29",
        "siteURL": "https://www.tesla.com",
        "industries": ["Automotive", "Energy"],
        "icon": "https://logo.clearbit.com/tesla.com",
        "favorited": false,
        "timesBought": 300
    },
    {
        "id": 6,
        "ticker": "FB",
        "exchange": "NASDAQ",
        "name": "Meta Platforms, Inc.",
        "initialPrice": 38.00,
        "currentPrice": 355.00,
        "description": "Meta Platforms, Inc., formerly known as Facebook, Inc., is an American multinational technology conglomerate based in Menlo Park, California.",
        "ipoDate": "2012-05-18",
        "siteURL": "https://www.meta.com",
        "industries": ["Technology", "Social Media"],
        "icon": "https://logo.clearbit.com/meta.com",
        "favorited": true,
        "timesBought": 250
    },
    {
        "id": 7,
        "ticker": "NFLX",
        "exchange": "NASDAQ",
        "name": "Netflix, Inc.",
        "initialPrice": 15.00,
        "currentPrice": 550.00,
        "description": "Netflix, Inc. is an American subscription streaming service and production company.",
        "ipoDate": "2002-05-23",
        "siteURL": "https://www.netflix.com",
        "industries": ["Entertainment", "Streaming"],
        "icon": "https://logo.clearbit.com/netflix.com",
        "favorited": false,
        "timesBought": 220
    },
    {
        "id": 8,
        "ticker": "NVDA",
        "exchange": "NASDAQ",
        "name": "NVIDIA Corporation",
        "initialPrice": 12.00,
        "currentPrice": 800.00,
        "description": "NVIDIA Corporation is an American multinational technology company incorporated in Delaware and based in Santa Clara, California.",
        "ipoDate": "1999-01-22",
        "siteURL": "https://www.nvidia.com",
        "industries": ["Technology", "Semiconductors"],
        "icon": "https://logo.clearbit.com/nvidia.com",
        "favorited": true,
        "timesBought": 210
    },
    {
        "id": 9,
        "ticker": "INTC",
        "exchange": "NASDAQ",
        "name": "Intel Corporation",
        "initialPrice": 23.50,
        "currentPrice": 54.00,
        "description": "Intel Corporation is an American multinational corporation and technology company headquartered in Santa Clara, California.",
        "ipoDate": "1971-10-13",
        "siteURL": "https://www.intel.com",
        "industries": ["Technology", "Semiconductors"],
        "icon": "https://logo.clearbit.com/intel.com",
        "favorited": false,
        "timesBought": 130
    },
    {
        "id": 10,
        "ticker": "AMD",
        "exchange": "NASDAQ",
        "name": "Advanced Micro Devices, Inc.",
        "initialPrice": 16.00,
        "currentPrice": 85.00,
        "description": "Advanced Micro Devices, Inc. is an American multinational semiconductor company based in Santa Clara, California.",
        "ipoDate": "1972-09-27",
        "siteURL": "https://www.amd.com",
        "industries": ["Technology", "Semiconductors"],
        "icon": "https://logo.clearbit.com/amd.com",
        "favorited": true,
        "timesBought": 175
    },
    {
        "id": 11,
        "ticker": "BABA",
        "exchange": "NYSE",
        "name": "Alibaba Group Holding Limited",
        "initialPrice": 68.00,
        "currentPrice": 250.00,
        "description": "Alibaba Group Holding Limited is a Chinese multinational technology company specializing in e-commerce, retail, Internet, and technology.",
        "ipoDate": "2014-09-19",
        "siteURL": "https://www.alibaba.com",
        "industries": ["Technology", "E-commerce"],
        "icon": "https://logo.clearbit.com/alibaba.com",
        "favorited": false,
        "timesBought": 140
    },
    {
        "id": 12,
        "ticker": "ORCL",
        "exchange": "NYSE",
        "name": "Oracle Corporation",
        "initialPrice": 15.00,
        "currentPrice": 85.00,
        "description": "Oracle Corporation is an American multinational computer technology corporation headquartered in Austin, Texas.",
        "ipoDate": "1986-03-12",
        "siteURL": "https://www.oracle.com",
        "industries": ["Technology", "Software"],
        "icon": "https://logo.clearbit.com/oracle.com",
        "favorited": true,
        "timesBought": 160
    },
    {
        "id": 13,
        "ticker": "CSCO",
        "exchange": "NASDAQ",
        "name": "Cisco Systems, Inc.",
        "initialPrice": 18.00,
        "currentPrice": 55.00,
        "description": "Cisco Systems, Inc. is an American multinational technology conglomerate headquartered in San Jose, California.",
        "ipoDate": "1990-02-16",
        "siteURL": "https://www.cisco.com",
        "industries": ["Technology", "Networking"],
        "icon": "https://logo.clearbit.com/cisco.com",
        "favorited": false,
        "timesBought": 125
    },
    {
        "id": 14,
        "ticker": "IBM",
        "exchange": "NYSE",
        "name": "International Business Machines Corporation",
        "initialPrice": 28.12,
        "currentPrice": 144.00,
        "description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York.",
        "ipoDate": "1911-06-16",
        "siteURL": "https://www.ibm.com",
        "industries": ["Technology", "Consulting"],
        "icon":

 "https://logo.clearbit.com/ibm.com",
        "favorited": true,
        "timesBought": 170
    },
    {
        "id": 15,
        "ticker": "SAP",
        "exchange": "NYSE",
        "name": "SAP SE",
        "initialPrice": 34.00,
        "currentPrice": 150.00,
        "description": "SAP SE is a German multinational software corporation based in Walldorf, Baden-Württemberg, that develops enterprise software to manage business operations and customer relations.",
        "ipoDate": "1988-11-04",
        "siteURL": "https://www.sap.com",
        "industries": ["Technology", "Software"],
        "icon": "https://logo.clearbit.com/sap.com",
        "favorited": false,
        "timesBought": 145
    },
    {
        "id": 16,
        "ticker": "ADBE",
        "exchange": "NASDAQ",
        "name": "Adobe Inc.",
        "initialPrice": 11.00,
        "currentPrice": 680.00,
        "description": "Adobe Inc. is an American multinational computer software company headquartered in San Jose, California.",
        "ipoDate": "1986-08-20",
        "siteURL": "https://www.adobe.com",
        "industries": ["Technology", "Software"],
        "icon": "https://logo.clearbit.com/adobe.com",
        "favorited": true,
        "timesBought": 190
    },
    {
        "id": 17,
        "ticker": "UBER",
        "exchange": "NYSE",
        "name": "Uber Technologies, Inc.",
        "initialPrice": 45.00,
        "currentPrice": 70.00,
        "description": "Uber Technologies, Inc. is an American technology company. Its services include ride-hailing, food delivery (Uber Eats), package delivery, couriers, freight transportation, and a partnership with Lime scooters and bikes.",
        "ipoDate": "2019-05-10",
        "siteURL": "https://www.uber.com",
        "industries": ["Technology", "Transportation"],
        "icon": "https://logo.clearbit.com/uber.com",
        "favorited": false,
        "timesBought": 115
    },
    {
        "id": 18,
        "ticker": "LYFT",
        "exchange": "NASDAQ",
        "name": "Lyft, Inc.",
        "initialPrice": 72.00,
        "currentPrice": 55.00,
        "description": "Lyft, Inc. is an American transport network company based in San Francisco, California, and operating in 644 cities in the United States and 12 cities in Canada.",
        "ipoDate": "2019-03-29",
        "siteURL": "https://www.lyft.com",
        "industries": ["Technology", "Transportation"],
        "icon": "https://logo.clearbit.com/lyft.com",
        "favorited": true,
        "timesBought": 100
    },
    {
        "id": 19,
        "ticker": "PYPL",
        "exchange": "NASDAQ",
        "name": "PayPal Holdings, Inc.",
        "initialPrice": 13.00,
        "currentPrice": 300.00,
        "description": "PayPal Holdings, Inc. is an American company operating an online payments system in the majority of countries that support online money transfers.",
        "ipoDate": "2015-07-20",
        "siteURL": "https://www.paypal.com",
        "industries": ["Technology", "Finance"],
        "icon": "https://logo.clearbit.com/paypal.com",
        "favorited": false,
        "timesBought": 220
    },
    {
        "id": 20,
        "ticker": "SQ",
        "exchange": "NYSE",
        "name": "Square, Inc.",
        "initialPrice": 9.00,
        "currentPrice": 240.00,
        "description": "Square, Inc. is an American financial services and mobile payment company based in San Francisco, California.",
        "ipoDate": "2015-11-19",
        "siteURL": "https://www.squareup.com",
        "industries": ["Technology", "Finance"],
        "icon": "https://logo.clearbit.com/squareup.com",
        "favorited": true,
        "timesBought": 185
    },
    {
        "id": 21,
        "ticker": "SHOP",
        "exchange": "NYSE",
        "name": "Shopify Inc.",
        "initialPrice": 17.00,
        "currentPrice": 1500.00,
        "description": "Shopify Inc. is a Canadian multinational e-commerce company headquartered in Ottawa, Ontario.",
        "ipoDate": "2015-05-21",
        "siteURL": "https://www.shopify.com",
        "industries": ["Technology", "E-commerce"],
        "icon": "https://logo.clearbit.com/shopify.com",
        "favorited": false,
        "timesBought": 205
    },
    {
        "id": 22,
        "ticker": "TWTR",
        "exchange": "NYSE",
        "name": "Twitter, Inc.",
        "initialPrice": 26.00,
        "currentPrice": 70.00,
        "description": "Twitter, Inc. is an American microblogging and social networking service on which users post and interact with messages known as tweets.",
        "ipoDate": "2013-11-07",
        "siteURL": "https://www.twitter.com",
        "industries": ["Technology", "Social Media"],
        "icon": "https://logo.clearbit.com/twitter.com",
        "favorited": true,
        "timesBought": 195
    },
    {
        "id": 23,
        "ticker": "SNAP",
        "exchange": "NYSE",
        "name": "Snap Inc.",
        "initialPrice": 17.00,
        "currentPrice": 60.00,
        "description": "Snap Inc. is an American camera and social media company, founded on September 16, 2011, by Evan Spiegel, Bobby Murphy, and Reggie Brown based in Santa Monica, California.",
        "ipoDate": "2017-03-02",
        "siteURL": "https://www.snapchat.com",
        "industries": ["Technology", "Social Media"],
        "icon": "https://logo.clearbit.com/snapchat.com",
        "favorited": false,
        "timesBought": 170
    },
    {
        "id": 24,
        "ticker": "ZM",
        "exchange": "NASDAQ",
        "name": "Zoom Video Communications, Inc.",
        "initialPrice": 36.00,
        "currentPrice": 380.00,
        "description": "Zoom Video Communications, Inc. is an American communications technology company headquartered in San Jose, California.",
        "ipoDate": "2019-04-18",
        "siteURL": "https://www.zoom.us",
        "industries": ["Technology", "Communications"],
        "icon": "https://logo.clearbit.com/zoom.us",
        "favorited": true,
        "timesBought": 240
    },
    {
        "id": 25,
        "ticker": "SPOT",
        "exchange": "NYSE",
        "name": "Spotify Technology S.A.",
        "initialPrice": 132.00,
        "currentPrice": 275.00,
        "description": "Spotify Technology S.A. is a Swedish audio streaming and media services provider founded in 2006 by Daniel Ek.",
        "ipoDate": "2018-04-03",
        "siteURL": "https://www.spotify.com",
        "industries": ["Technology", "Entertainment"],
        "icon": "https://logo.clearbit.com/spotify.com",
        "favorited": false,
        "timesBought": 160
    },
    {
        "id": 26,
        "ticker": "UBI",
        "exchange": "NYSE",
        "name": "Ubisoft Entertainment S.A.",
        "initialPrice": 15.00,
        "currentPrice": 55.00,
        "description": "Ubisoft Entertainment S.A. is a French video game company headquartered in Montreuil with several development studios across the world.",
        "ipoDate": "1996-07-01",
        "siteURL": "https://www.ubisoft.com",
        "industries": ["Technology", "Entertainment"],
        "icon": "https://logo.clearbit.com/ubisoft.com",
        "favorited": true,
        "timesBought": 145
    },
    {
        "id": 27,
        "ticker": "EA",
        "exchange": "NASDAQ",
        "name": "Electronic Arts Inc.",
        "initialPrice": 21.00,
        "currentPrice": 150.00,
        "description": "Electronic Arts Inc. is an American video game company headquartered in Redwood City, California.",
        "ipoDate": "1989-09-20",
        "siteURL": "https://www.ea.com",
        "industries": ["Technology", "Entertainment"],
        "icon": "https://logo.clearbit.com/ea.com",
        "favorited": false,
        "timesBought": 200
    }
]
    